### ISSUE TITLE
Created ServiceMonitor has incorrect matchLabel 

### ISSUE THREAD

**Issue by seabaylea** [appsody/appsody-operator#182] opened 2019-11-14 14:08 UTC
### What did you do?

When deploying an Appsody Application that enables monitoring, the operator adds the following label onto the Application service:

```
app.appsody.dev/monitor: "true"
```

It then creates a ServiceMonitor with the following `matchLabel`:

```
app.appsody.dev/monitor:  true
```

The mismatch of the use of quotes around `true` means that the Service Monitor doesn't pick up the Appsody Application.

### What did you expect to see?

Monitoring data in Prometheus

### What did you see instead?

No monitoring data in Prometheus 

### Environment

* Appsody CLI version:

```
appsody 0.4.10
```

* Appsody Stack:

```
java-microprofile
```

* Kubernetes version information:

**Comment by arturdzm** [comment] 2019-11-14 14:30
I just  tested 0.2.2 and I see this on my 4.2 cluster in ServiceMonitor
Perhaps your issues with the `spec.monitoring.labels` not matching the Prometheus's CR `serviceMonitorSelector`

```
  selector:
    matchLabels:
      app.appsody.dev/monitor: 'true'
      app.kubernetes.io/name: example-appsodyapplication
```
Having no quotes would be a bool and illegal as the `MatchLabels` type is `map[string]string`
https://github.com/appsody/appsody-operator/blob/d035516488c2019108ea260cfb94b05e6a160827/pkg/utils/utils.go#L384

**Comment by arthurdm** [comment] 2020-04-17 19:43
Perhaps we can close this issue, if it's not a bug?

**Comment by arturdzm** [comment] 2020-04-17 23:25
Afaik it works  on 0.4.x I've recently had to use monitoring

**Closed by arturdzm** 2020-04-17 23:25 UTC
